import { mkdir, writeFile } from "fs/promises";
import path from "path";
import PDFDocument from "pdfkit/js/pdfkit.standalone";

interface LetterUser {
  _id?: string;
  fullName?: string;
  email?: string;
  phone?: string;
  nic?: string;
  employeeId?: string;
  department?: string;
  jobRole?: string;
}

interface LetterAdmin {
  _id?: string;
  fullName?: string;
  email?: string;
  role?: string;
  employeeId?: string;
}

interface LetterLoan {
  _id: string;
  userId?: LetterUser;
  adminId?: LetterAdmin;

  loanType?: string;
  supportType?: string;
  isRepayable?: boolean;

  requestedAmount?: number;
  approvedAmount?: number;
  purpose?: string;

  systemInterestRate?: number;
  preferredPeriodMonths?: number;
  approvedPeriodMonths?: number;
  monthlyInstallment?: number;
  totalRepayment?: number;
  remainingBalance?: number;

  riskLevel?: string;
  eligibilityStatus?: string;
  status?: string;

  officerRemark?: string;
  adminRemark?: string;

  createdAt?: Date | string;
  adminApprovedAt?: Date | string | null;
}

interface GenerateLoanApprovalLetterParams {
  loan: LetterLoan;
  admin: LetterAdmin;
}

const PAGE_WIDTH = 595.28;
const PAGE_MARGIN = 50;
const CONTENT_WIDTH = PAGE_WIDTH - PAGE_MARGIN * 2;
const FOOTER_Y = 790;

const colors = {
  navy: "#020817",
  navyLight: "#0f172a",
  blue: "#2563eb",
  cyan: "#06b6d4",
  cyanLight: "#cffafe",
  slate: "#334155",
  slateLight: "#64748b",
  border: "#dbeafe",
  softBlue: "#eff6ff",
  softGreen: "#ecfdf5",
  green: "#047857",
  red: "#b91c1c",
  white: "#ffffff",
};

const formatCurrency = (amount?: number) => {
  if (amount === undefined || amount === null) {
    return "LKR 0";
  }

  return `LKR ${amount.toLocaleString("en-LK")}`;
};

const formatDate = (date?: Date | string | null) => {
  if (!date) return "N/A";

  return new Date(date).toLocaleString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
};

const valueOrNA = (value?: string | number | null) => {
  if (value === undefined || value === null || value === "") {
    return "N/A";
  }

  return String(value);
};

const formatReadable = (value?: string | number | null) => {
  return valueOrNA(value).replaceAll("_", " ");
};

function addFooter(doc: PDFKit.PDFDocument, pageLabel = "Official Document") {
  doc
    .moveTo(PAGE_MARGIN, FOOTER_Y - 14)
    .lineTo(PAGE_WIDTH - PAGE_MARGIN, FOOTER_Y - 14)
    .strokeColor("#e2e8f0")
    .lineWidth(1)
    .stroke();

  doc
    .font("Helvetica")
    .fontSize(8)
    .fillColor(colors.slateLight)
    .text(`Generated by Welfare - ${pageLabel}`, PAGE_MARGIN, FOOTER_Y, {
      width: CONTENT_WIDTH / 2,
      align: "left",
    });

  doc
    .font("Helvetica")
    .fontSize(8)
    .fillColor(colors.slateLight)
    .text("This is a system generated document.", PAGE_MARGIN, FOOTER_Y, {
      width: CONTENT_WIDTH,
      align: "right",
    });
}

function ensureSpace(
  doc: PDFKit.PDFDocument,
  neededHeight = 120,
  footerLabel = "Official Document"
) {
  if (doc.y + neededHeight > FOOTER_Y - 25) {
    addFooter(doc, footerLabel);
    doc.addPage();
  }
}

function addHeader(
  doc: PDFKit.PDFDocument,
  title: string,
  referenceId: string,
  isFuneralSupport: boolean
) {
  doc.rect(0, 0, PAGE_WIDTH, 142).fill(colors.navy);

  doc
    .circle(PAGE_WIDTH - 85, 45, 48)
    .fillColor(isFuneralSupport ? "#065f46" : "#1d4ed8")
    .fillOpacity(0.35)
    .fill();

  doc.fillOpacity(1);

  doc
    .font("Helvetica-Bold")
    .fontSize(11)
    .fillColor(colors.cyanLight)
    .text("WELFARE MANAGEMENT SYSTEM", PAGE_MARGIN, 28, {
      characterSpacing: 1.8,
    });

  doc
    .font("Helvetica-Bold")
    .fontSize(24)
    .fillColor(colors.white)
    .text(title, PAGE_MARGIN, 52, {
      width: 360,
    });

  doc
    .font("Helvetica")
    .fontSize(9)
    .fillColor("#bfdbfe")
    .text("Official approval document generated by the Welfare platform", PAGE_MARGIN, 83, {
      width: 380,
    });

  doc
    .roundedRect(PAGE_WIDTH - 220, 35, 170, 72, 14)
    .fillAndStroke("#0f172a", "#334155");

  doc
    .font("Helvetica-Bold")
    .fontSize(9)
    .fillColor("#93c5fd")
    .text("REFERENCE ID", PAGE_WIDTH - 200, 51);

  doc
    .font("Helvetica-Bold")
    .fontSize(9)
    .fillColor(colors.white)
    .text(referenceId, PAGE_WIDTH - 200, 66, {
      width: 130,
      ellipsis: true,
    });

  doc
    .font("Helvetica")
    .fontSize(8)
    .fillColor("#cbd5e1")
    .text(`Generated: ${formatDate(new Date())}`, PAGE_WIDTH - 200, 85, {
      width: 135,
    });

  doc.y = 168;
}

function addDocumentStatusBox(
  doc: PDFKit.PDFDocument,
  isFuneralSupport: boolean
) {
  const statusTitle = isFuneralSupport
    ? "APPROVED FUNERAL SUPPORT"
    : "APPROVED LOAN OFFER";

  const statusText = isFuneralSupport
    ? "This request has been approved by Main Admin and forwarded to Finance Officer for grant disbursement processing."
    : "This loan has been approved by Main Admin and is waiting for member acceptance before finance processing.";

  const boxColor = isFuneralSupport ? colors.softGreen : colors.softBlue;
  const borderColor = isFuneralSupport ? "#bbf7d0" : "#bfdbfe";
  const titleColor = isFuneralSupport ? colors.green : colors.blue;

  doc
    .roundedRect(PAGE_MARGIN, doc.y, CONTENT_WIDTH, 74, 14)
    .fillAndStroke(boxColor, borderColor);

  const boxY = doc.y - 74;

  doc
    .font("Helvetica-Bold")
    .fontSize(11)
    .fillColor(titleColor)
    .text(statusTitle, PAGE_MARGIN + 18, boxY + 16);

  doc
    .font("Helvetica")
    .fontSize(9.5)
    .fillColor(isFuneralSupport ? "#065f46" : "#1e3a8a")
    .text(statusText, PAGE_MARGIN + 18, boxY + 36, {
      width: CONTENT_WIDTH - 36,
      lineGap: 3,
    });

  doc.moveDown(2.2);
}

function addSectionTitle(doc: PDFKit.PDFDocument, title: string) {
  ensureSpace(doc, 90);

  doc.moveDown(0.4);

  doc
    .font("Helvetica-Bold")
    .fontSize(13)
    .fillColor(colors.navyLight)
    .text(title, PAGE_MARGIN, doc.y);

  doc
    .moveTo(PAGE_MARGIN, doc.y + 5)
    .lineTo(PAGE_WIDTH - PAGE_MARGIN, doc.y + 5)
    .strokeColor(colors.border)
    .lineWidth(1)
    .stroke();

  doc.moveDown(0.9);
}

function addInfoTable(
  doc: PDFKit.PDFDocument,
  rows: Array<[string, string | number | undefined | null]>
) {
  const rowHeight = 28;
  const labelWidth = 170;
  const valueWidth = CONTENT_WIDTH - labelWidth;

  rows.forEach(([label, value], index) => {
    ensureSpace(doc, rowHeight + 20);

    const y = doc.y;
    const fill = index % 2 === 0 ? "#f8fafc" : "#ffffff";

    doc
      .roundedRect(PAGE_MARGIN, y, CONTENT_WIDTH, rowHeight, 6)
      .fillAndStroke(fill, "#e2e8f0");

    doc
      .font("Helvetica-Bold")
      .fontSize(9)
      .fillColor(colors.slate)
      .text(label, PAGE_MARGIN + 12, y + 9, {
        width: labelWidth - 20,
      });

    doc
      .font("Helvetica")
      .fontSize(9)
      .fillColor(colors.navyLight)
      .text(valueOrNA(value), PAGE_MARGIN + labelWidth + 10, y + 9, {
        width: valueWidth - 22,
        ellipsis: true,
      });

    doc.y = y + rowHeight + 4;
  });

  doc.moveDown(0.4);
}

function addSummaryCards(
  doc: PDFKit.PDFDocument,
  cards: Array<{
    label: string;
    value: string;
    tone?: "blue" | "green" | "orange";
  }>
) {
  ensureSpace(doc, 100);

  const gap = 10;
  const cardWidth = (CONTENT_WIDTH - gap * 2) / 3;
  const cardHeight = 70;
  const y = doc.y;

  cards.slice(0, 3).forEach((card, index) => {
    const x = PAGE_MARGIN + index * (cardWidth + gap);

    const borderColor =
      card.tone === "green"
        ? "#bbf7d0"
        : card.tone === "orange"
          ? "#fed7aa"
          : "#bfdbfe";

    const textColor =
      card.tone === "green"
        ? colors.green
        : card.tone === "orange"
          ? "#c2410c"
          : colors.blue;

    const fillColor =
      card.tone === "green"
        ? colors.softGreen
        : card.tone === "orange"
          ? "#fff7ed"
          : colors.softBlue;

    doc.roundedRect(x, y, cardWidth, cardHeight, 12).fillAndStroke(fillColor, borderColor);

    doc
      .font("Helvetica-Bold")
      .fontSize(8)
      .fillColor(colors.slate)
      .text(card.label.toUpperCase(), x + 12, y + 14, {
        width: cardWidth - 24,
      });

    doc
      .font("Helvetica-Bold")
      .fontSize(13)
      .fillColor(textColor)
      .text(card.value, x + 12, y + 34, {
        width: cardWidth - 24,
      });
  });

  doc.y = y + cardHeight + 16;
}

function addParagraphBox(
  doc: PDFKit.PDFDocument,
  title: string,
  body: string,
  tone: "blue" | "green" = "blue"
) {
  ensureSpace(doc, 125);

  const fill = tone === "green" ? colors.softGreen : colors.softBlue;
  const border = tone === "green" ? "#bbf7d0" : "#bfdbfe";
  const titleColor = tone === "green" ? colors.green : colors.blue;
  const bodyColor = tone === "green" ? "#065f46" : "#1e3a8a";

  const startY = doc.y;

  doc.roundedRect(PAGE_MARGIN, startY, CONTENT_WIDTH, 92, 14).fillAndStroke(fill, border);

  doc
    .font("Helvetica-Bold")
    .fontSize(11)
    .fillColor(titleColor)
    .text(title, PAGE_MARGIN + 18, startY + 16);

  doc
    .font("Helvetica")
    .fontSize(9.5)
    .fillColor(bodyColor)
    .text(body, PAGE_MARGIN + 18, startY + 38, {
      width: CONTENT_WIDTH - 36,
      lineGap: 3,
    });

  doc.y = startY + 106;
}

function addTerms(doc: PDFKit.PDFDocument, terms: string[]) {
  terms.forEach((term, index) => {
    ensureSpace(doc, 40);

    doc
      .font("Helvetica-Bold")
      .fontSize(9)
      .fillColor(colors.blue)
      .text(`${index + 1}.`, PAGE_MARGIN, doc.y, {
        continued: true,
      });

    doc
      .font("Helvetica")
      .fontSize(9)
      .fillColor(colors.navyLight)
      .text(` ${term}`, {
        width: CONTENT_WIDTH - 20,
        lineGap: 3,
      });

    doc.moveDown(0.35);
  });
}

function addSignatureSection(
  doc: PDFKit.PDFDocument,
  admin: LetterAdmin,
  isFuneralSupport: boolean
) {
  ensureSpace(doc, 150);

  const y = doc.y + 8;
  const boxWidth = (CONTENT_WIDTH - 20) / 2;

  doc
    .roundedRect(PAGE_MARGIN, y, boxWidth, 95, 12)
    .fillAndStroke("#ffffff", "#e2e8f0");

  doc
    .font("Helvetica-Bold")
    .fontSize(10)
    .fillColor(colors.navyLight)
    .text("Authorized By", PAGE_MARGIN + 14, y + 14);

  doc
    .font("Helvetica")
    .fontSize(9)
    .fillColor(colors.slate)
    .text(valueOrNA(admin.fullName), PAGE_MARGIN + 14, y + 34)
    .text(valueOrNA(admin.email), PAGE_MARGIN + 14, y + 50)
    .text(`Employee ID: ${valueOrNA(admin.employeeId)}`, PAGE_MARGIN + 14, y + 66);

  doc
    .roundedRect(PAGE_MARGIN + boxWidth + 20, y, boxWidth, 95, 12)
    .fillAndStroke("#ffffff", "#e2e8f0");

  doc
    .font("Helvetica-Bold")
    .fontSize(10)
    .fillColor(colors.navyLight)
    .text(isFuneralSupport ? "Finance Action" : "Member Action", PAGE_MARGIN + boxWidth + 34, y + 14);

  doc
    .font("Helvetica")
    .fontSize(9)
    .fillColor(colors.slate)
    .text(
      isFuneralSupport
        ? "Forwarded to Finance Officer for disbursement processing."
        : "Member must review this offer and accept or reject from the dashboard.",
      PAGE_MARGIN + boxWidth + 34,
      y + 36,
      {
        width: boxWidth - 28,
        lineGap: 3,
      }
    );

  doc.y = y + 115;
}

export async function generateLoanApprovalLetter({
  loan,
  admin,
}: GenerateLoanApprovalLetterParams) {
  const loanId = loan._id.toString();

  const isFuneralSupport =
    loan.loanType === "Funeral Support Loan" ||
    loan.supportType === "non_repayable_grant" ||
    loan.isRepayable === false;

  const documentTitle = isFuneralSupport
    ? "Funeral Support Approval Letter"
    : "Loan Approval Offer Letter";

  const letterDir = path.join(
    process.cwd(),
    "public",
    "reports",
    "loan-approval-letters"
  );

  await mkdir(letterDir, { recursive: true });

  const fileName = `${loanId}-loan-approval-letter.pdf`;
  const filePath = path.join(letterDir, fileName);
  const letterUrl = `/reports/loan-approval-letters/${fileName}`;

  const pdfBuffer = await new Promise<Buffer>((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: "A4",
        margin: PAGE_MARGIN,
        info: {
          Title: documentTitle,
          Author: "Welfare",
          Subject: documentTitle,
        },
      });

      const chunks: Buffer[] = [];

      doc.on("data", (chunk: Buffer) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      addHeader(doc, documentTitle, loanId, isFuneralSupport);
      addDocumentStatusBox(doc, isFuneralSupport);

      addSummaryCards(doc, [
        {
          label: "Approved Amount",
          value: formatCurrency(loan.approvedAmount),
          tone: "blue",
        },
        {
          label: isFuneralSupport ? "Repayment Type" : "Monthly EMI",
          value: isFuneralSupport
            ? "Non-repayable"
            : formatCurrency(loan.monthlyInstallment),
          tone: "green",
        },
        {
          label: isFuneralSupport ? "Finance Status" : "Repayment Period",
          value: isFuneralSupport
            ? "Processing"
            : `${loan.approvedPeriodMonths || loan.preferredPeriodMonths || 0} months`,
          tone: "orange",
        },
      ]);

      addSectionTitle(doc, "1. Member Details");

      addInfoTable(doc, [
        ["Full Name", loan.userId?.fullName],
        ["Email Address", loan.userId?.email],
        ["Phone Number", loan.userId?.phone],
        ["NIC Number", loan.userId?.nic],
        ["Employee ID", loan.userId?.employeeId],
        ["Department", loan.userId?.department],
        ["Job Role", loan.userId?.jobRole],
      ]);

      addSectionTitle(
        doc,
        isFuneralSupport
          ? "2. Approved Funeral Support Details"
          : "2. Approved Loan Offer Details"
      );

      const financialRows: Array<[string, string | number | undefined | null]> = [
        ["Request Type", isFuneralSupport ? "Funeral Support Grant" : loan.loanType],
        ["Purpose / Reason", loan.purpose],
        ["Requested Amount", formatCurrency(loan.requestedAmount)],
        ["Approved Amount", formatCurrency(loan.approvedAmount)],
      ];

      if (isFuneralSupport) {
        financialRows.push(
          ["Repayment Type", "Non-repayable welfare support"],
          ["Interest Rate", "0%"],
          ["Repayment Period", "Not applicable"],
          ["Monthly EMI", "Not applicable"],
          ["Total Repayment", "Not applicable"],
          ["Remaining Balance", "LKR 0"]
        );
      } else {
        financialRows.push(
          ["Interest Rate", `${loan.systemInterestRate || 0}%`],
          [
            "Repayment Period",
            `${loan.approvedPeriodMonths || loan.preferredPeriodMonths || 0} months`,
          ],
          ["Monthly EMI", formatCurrency(loan.monthlyInstallment)],
          ["Total Repayment", formatCurrency(loan.totalRepayment)],
          ["Remaining Balance", formatCurrency(loan.remainingBalance)]
        );
      }

      financialRows.push(
        ["Risk Level", formatReadable(loan.riskLevel)],
        ["Eligibility Status", formatReadable(loan.eligibilityStatus)]
      );

      addInfoTable(doc, financialRows);

      addSectionTitle(doc, "3. Approval Summary");

      addInfoTable(doc, [
        [
          "Approval Status",
          isFuneralSupport
            ? "Approved - Forwarded to Finance Processing"
            : "Approved - Waiting for Member Acceptance",
        ],
        ["Admin Approved At", formatDate(loan.adminApprovedAt)],
        ["Admin Name", admin.fullName],
        ["Admin Email", admin.email],
        ["Admin Employee ID", admin.employeeId],
        ["Officer Remark", loan.officerRemark || "N/A"],
        ["Admin Remark", loan.adminRemark || "N/A"],
      ]);

      addSectionTitle(
        doc,
        isFuneralSupport ? "4. Finance Processing Notice" : "4. Member Action Required"
      );

      addParagraphBox(
        doc,
        "Important Notice",
        isFuneralSupport
          ? "Your funeral support request has been approved by Main Admin. This is a non-repayable welfare support grant. The request has been forwarded to the Finance Officer for disbursement processing. This support amount does not create an installment schedule, interest charge, repayment balance, or monthly EMI."
          : "Your loan application has been approved by Main Admin. Please review the approved loan amount, interest rate, repayment period, monthly installment, and total repayment amount carefully. If you agree with these terms, accept the offer from your member dashboard. Accepting this offer will forward your loan to the Finance Officer for disbursement processing.",
        isFuneralSupport ? "green" : "blue"
      );

      addSectionTitle(doc, "5. Terms and Conditions");

      const terms = isFuneralSupport
        ? [
            "This funeral support is a non-repayable welfare benefit.",
            "The approved amount is subject to finance processing and organizational welfare policy.",
            "The welfare organization may verify additional documents before final disbursement.",
            "False, invalid, or misleading documents may result in rejection or cancellation of the request.",
            "The final disbursement record will be maintained by the Finance Officer.",
          ]
        : [
            "The member must accept this loan offer before finance processing begins.",
            "The member agrees to repay the loan according to the approved repayment schedule.",
            "Monthly installments must be paid before or on the due date.",
            "Late payments may be subject to penalties according to welfare policy.",
            "The welfare organization may verify additional details before final disbursement.",
          ];

      addTerms(doc, terms);

      addSectionTitle(doc, "6. Authorization");

      addSignatureSection(doc, admin, isFuneralSupport);

      addFooter(doc, documentTitle);
      doc.end();
    } catch (error) {
      reject(error);
    }
  });

  await writeFile(filePath, pdfBuffer);

  return {
    letterUrl,
    filePath,
  };
}