import { mkdir, writeFile } from "fs/promises";
import path from "path";
import PDFDocument from "pdfkit/js/pdfkit.standalone";

interface ReportUser {
  _id?: string;
  fullName?: string;
  email?: string;
  phone?: string;
  nic?: string;
  employeeId?: string;
  department?: string;
  jobRole?: string;
  role?: string;
}

interface ReportDocument {
  label?: string;
  documentType?: string;
  originalName?: string;
  fileName?: string;
  status?: string;
  verifiedAt?: Date | string | null;
  remark?: string;
}

interface ReportLoan {
  _id: string;
  userId?: ReportUser;
  welfareOfficerId?: ReportUser;

  loanType?: string;
  requestedAmount?: number;
  approvedAmount?: number;
  purpose?: string;
  monthlyIncome?: number;
  employmentType?: string;

  guarantorName?: string;
  guarantorPhone?: string;
  guarantorNic?: string;

  systemInterestRate?: number;
  preferredPeriodMonths?: number;
  recommendedPeriodMonths?: number;
  monthlyInstallment?: number;
  totalRepayment?: number;

  riskLevel?: string;
  eligibilityStatus?: string;
  documentStatus?: string;
  status?: string;

  officerRemark?: string;
  createdAt?: Date | string;
  updatedAt?: Date | string;
}

interface GenerateOfficerLoanReportParams {
  loan: ReportLoan;
  documents: ReportDocument[];
  officer: ReportUser;
}

const formatCurrency = (amount?: number) => {
  if (amount === undefined || amount === null) {
    return "LKR 0";
  }

  return `LKR ${amount.toLocaleString("en-LK")}`;
};

const formatDate = (date?: Date | string | null) => {
  if (!date) return "N/A";

  return new Date(date).toLocaleString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
};

const valueOrNA = (value?: string | number | null) => {
  if (value === undefined || value === null || value === "") {
    return "N/A";
  }

  return String(value);
};

function addSectionTitle(doc: PDFKit.PDFDocument, title: string) {
  doc.moveDown(1.1);

  doc.font("Helvetica-Bold").fontSize(14).fillColor("#0f172a").text(title);

  doc
    .moveTo(doc.x, doc.y + 4)
    .lineTo(545, doc.y + 4)
    .strokeColor("#dbeafe")
    .lineWidth(1)
    .stroke();

  doc.moveDown(0.8);
}

function addRow(
  doc: PDFKit.PDFDocument,
  label: string,
  value?: string | number
) {
  const startX = 55;
  const labelWidth = 170;
  const valueWidth = 320;
  const y = doc.y;

  doc
    .font("Helvetica-Bold")
    .fontSize(10)
    .fillColor("#334155")
    .text(label, startX, y, {
      width: labelWidth,
    });

  doc
    .font("Helvetica")
    .fontSize(10)
    .fillColor("#0f172a")
    .text(valueOrNA(value), startX + labelWidth + 15, y, {
      width: valueWidth,
    });

  doc.moveDown(0.65);
}

function addFooter(doc: PDFKit.PDFDocument) {
  const bottom = 760;

  doc
    .font("Helvetica")
    .fontSize(8)
    .fillColor("#64748b")
    .text(
      "Generated by Welfare System - Welfare Officer Review Report",
      55,
      bottom,
      {
        align: "center",
        width: 490,
      }
    );
}

function ensureSpace(doc: PDFKit.PDFDocument, neededHeight = 120) {
  if (doc.y + neededHeight > 740) {
    addFooter(doc);
    doc.addPage();
  }
}

export async function generateOfficerLoanReport({
  loan,
  documents,
  officer,
}: GenerateOfficerLoanReportParams) {
  const loanId = loan._id.toString();

  const reportDir = path.join(
    process.cwd(),
    "public",
    "reports",
    "officer-loan-reviews"
  );

  await mkdir(reportDir, { recursive: true });

  const fileName = `${loanId}-officer-review.pdf`;
  const filePath = path.join(reportDir, fileName);
  const reportUrl = `/reports/officer-loan-reviews/${fileName}`;

  const pdfBuffer = await new Promise<Buffer>((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: "A4",
        margin: 55,
        info: {
          Title: "Welfare Officer Review Report",
          Author: "Welfare System",
          Subject: "Loan Application Review",
        },
      });

      const chunks: Buffer[] = [];

      doc.on("data", (chunk: Buffer) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      doc.rect(0, 0, 595.28, 110).fill("#020817");

      doc
        .fillColor("#ffffff")
        .font("Helvetica-Bold")
        .fontSize(22)
        .text("Welfare Officer Review Report", 55, 35);

      doc
        .font("Helvetica")
        .fontSize(10)
        .fillColor("#bfdbfe")
        .text(`Loan ID: ${loanId}`, 55, 65)
        .text(`Generated At: ${formatDate(new Date())}`, 55, 82);

      doc.moveDown(3);

      addSectionTitle(doc, "1. Loan Application Summary");

      addRow(doc, "Loan Type", loan.loanType);
      addRow(doc, "Application Status", loan.status?.replaceAll("_", " "));
      addRow(doc, "Requested Amount", formatCurrency(loan.requestedAmount));
      addRow(doc, "Approved Amount", formatCurrency(loan.approvedAmount));
      addRow(doc, "Monthly Installment", formatCurrency(loan.monthlyInstallment));
      addRow(doc, "Total Repayment", formatCurrency(loan.totalRepayment));
      addRow(doc, "Interest Rate", `${loan.systemInterestRate || 0}%`);
      addRow(
        doc,
        "Preferred Period",
        `${loan.preferredPeriodMonths || 0} months`
      );
      addRow(
        doc,
        "Recommended Period",
        `${loan.recommendedPeriodMonths || 0} months`
      );
      addRow(doc, "Risk Level", loan.riskLevel);
      addRow(
        doc,
        "Eligibility Status",
        loan.eligibilityStatus?.replaceAll("_", " ")
      );
      addRow(
        doc,
        "Document Status",
        loan.documentStatus?.replaceAll("_", " ")
      );

      ensureSpace(doc);

      addSectionTitle(doc, "2. Member Details");

      addRow(doc, "Full Name", loan.userId?.fullName);
      addRow(doc, "Email", loan.userId?.email);
      addRow(doc, "Phone", loan.userId?.phone);
      addRow(doc, "NIC", loan.userId?.nic);
      addRow(doc, "Employee ID", loan.userId?.employeeId);
      addRow(doc, "Department", loan.userId?.department);
      addRow(doc, "Job Role", loan.userId?.jobRole);

      ensureSpace(doc);

      addSectionTitle(doc, "3. Loan Purpose and Financial Assessment");

      addRow(doc, "Purpose", loan.purpose);
      addRow(doc, "Monthly Income", formatCurrency(loan.monthlyIncome));
      addRow(doc, "Employment Type", loan.employmentType);

      ensureSpace(doc);

      addSectionTitle(doc, "4. Guarantor Details");

      addRow(doc, "Guarantor Name", loan.guarantorName);
      addRow(doc, "Guarantor Phone", loan.guarantorPhone);
      addRow(doc, "Guarantor NIC", loan.guarantorNic);

      ensureSpace(doc);

      addSectionTitle(doc, "5. Document Verification Summary");

      if (documents.length === 0) {
        addRow(doc, "Documents", "No documents found");
      } else {
        documents.forEach((document, index) => {
          ensureSpace(doc, 80);

          doc
            .font("Helvetica-Bold")
            .fontSize(10)
            .fillColor("#0f172a")
            .text(`${index + 1}. ${document.label || document.documentType}`);

          doc.moveDown(0.35);

          addRow(
            doc,
            "File Name",
            document.originalName || document.fileName || "N/A"
          );
          addRow(doc, "Status", document.status?.replaceAll("_", " "));
          addRow(doc, "Verified At", formatDate(document.verifiedAt));
          addRow(doc, "Remark", document.remark || "N/A");

          doc.moveDown(0.35);
        });
      }

      ensureSpace(doc);

      addSectionTitle(doc, "6. Officer Review Decision");

      addRow(doc, "Officer Name", officer.fullName);
      addRow(doc, "Officer Email", officer.email);
      addRow(doc, "Officer Employee ID", officer.employeeId);
      addRow(doc, "Officer Role", officer.role?.replaceAll("_", " "));
      addRow(doc, "Officer Remark", loan.officerRemark || "N/A");
      addRow(doc, "Final Forward Status", "Forwarded to Admin Approval");

      doc.moveDown(1.5);

      const boxY = doc.y;

      doc.roundedRect(55, boxY, 490, 62, 12).fillAndStroke("#ecfdf5", "#bbf7d0");

      doc
        .font("Helvetica-Bold")
        .fontSize(12)
        .fillColor("#047857")
        .text("Officer Verification Completed", 75, boxY + 14);

      doc
        .font("Helvetica")
        .fontSize(10)
        .fillColor("#065f46")
        .text(
          "This report was generated automatically after the Welfare Officer completed document verification and forwarded the loan application to Main Admin for final approval.",
          75,
          boxY + 32,
          { width: 450 }
        );

      addFooter(doc);
      doc.end();
    } catch (error) {
      reject(error);
    }
  });

  await writeFile(filePath, pdfBuffer);

  return {
    reportUrl,
    filePath,
  };
}