import { NextResponse } from "next/server";
import PDFDocument from "pdfkit/js/pdfkit.standalone";

import dbConnect from "@/lib/dbConnect";
import { getCurrentUser } from "@/lib/getCurrentUser";

import User from "@/models/User";
import Loan from "@/models/Loan";

export const runtime = "nodejs";

const PAGE_WIDTH = 595.28;
const PAGE_MARGIN = 45;
const CONTENT_WIDTH = PAGE_WIDTH - PAGE_MARGIN * 2;
const FOOTER_Y = 790;

const colors = {
  navy: "#020817",
  blue: "#2563eb",
  white: "#ffffff",
  text: "#0f172a",
  muted: "#64748b",
  border: "#dbeafe",
  softBlue: "#eff6ff",
  softGreen: "#ecfdf5",
  softOrange: "#fff7ed",
  softRed: "#fef2f2",
  green: "#047857",
  orange: "#c2410c",
  red: "#b91c1c",
};

const loanBaseFilter = {
  isDeleted: { $ne: true },
};

const pendingStatuses = [
  "submitted",
  "under_welfare_review",
  "pending_admin_approval",
];

const approvedOrProcessingStatuses = [
  "admin_approved",
  "user_offer_pending",
  "user_accepted",
  "pending_finance_processing",
  "finance_approved",
  "disbursed",
  "active",
  "completed",
];

const disbursedStatuses = ["disbursed", "active", "completed"];

const rejectedStatuses = [
  "admin_rejected",
  "user_rejected",
  "welfare_rejected",
  "finance_rejected",
  "cancelled",
];

type RecentLoanRow = {
  type: string;
  member: string;
  amount: number;
  status: string;
  date?: Date | string;
};

type PopulatedLoanUser = {
  fullName?: string;
  email?: string;
  employeeId?: string;
};

const formatCurrency = (amount: number) => {
  return `LKR ${Number(amount || 0).toLocaleString("en-LK")}`;
};

const formatDate = (date?: Date | string | null) => {
  if (!date) return "N/A";

  return new Date(date).toLocaleString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
};

const formatStatus = (status?: string) => {
  return String(status || "unknown").replaceAll("_", " ");
};

function addFooter(doc: PDFKit.PDFDocument, pageNumber: number) {
  doc
    .moveTo(PAGE_MARGIN, FOOTER_Y - 12)
    .lineTo(PAGE_WIDTH - PAGE_MARGIN, FOOTER_Y - 12)
    .strokeColor("#e2e8f0")
    .lineWidth(1)
    .stroke();

  doc
    .font("Helvetica")
    .fontSize(8)
    .fillColor(colors.muted)
    .text(
      "Generated by Welfare - Admin Reports & Analytics",
      PAGE_MARGIN,
      FOOTER_Y,
      {
        width: CONTENT_WIDTH / 2,
        align: "left",
      }
    );

  doc
    .font("Helvetica")
    .fontSize(8)
    .fillColor(colors.muted)
    .text(`Page ${pageNumber}`, PAGE_MARGIN, FOOTER_Y, {
      width: CONTENT_WIDTH,
      align: "right",
    });
}

function ensureSpace(doc: PDFKit.PDFDocument, neededHeight = 70) {
  if (doc.y + neededHeight > FOOTER_Y - 25) {
    addFooter(doc, doc.bufferedPageRange().count);
    doc.addPage();
    doc.y = PAGE_MARGIN;
  }
}

function addHeader(doc: PDFKit.PDFDocument, adminName: string) {
  doc.rect(0, 0, PAGE_WIDTH, 120).fill(colors.navy);

  doc
    .font("Helvetica-Bold")
    .fontSize(10)
    .fillColor("#cffafe")
    .text("WELFARE MANAGEMENT SYSTEM", PAGE_MARGIN, 24, {
      characterSpacing: 1.5,
    });

  doc
    .font("Helvetica-Bold")
    .fontSize(24)
    .fillColor(colors.white)
    .text("Admin Reports & Analytics", PAGE_MARGIN, 48);

  doc
    .font("Helvetica")
    .fontSize(9)
    .fillColor("#bfdbfe")
    .text(
      "Official summary report generated from live database records",
      PAGE_MARGIN,
      80
    );

  doc
    .roundedRect(PAGE_WIDTH - 215, 32, 170, 62, 12)
    .fillAndStroke("#0f172a", "#334155");

  doc
    .font("Helvetica-Bold")
    .fontSize(8)
    .fillColor("#93c5fd")
    .text("GENERATED BY", PAGE_WIDTH - 195, 44);

  doc
    .font("Helvetica-Bold")
    .fontSize(9)
    .fillColor(colors.white)
    .text(adminName || "Main Admin", PAGE_WIDTH - 195, 58, {
      width: 130,
      ellipsis: true,
    });

  doc
    .font("Helvetica")
    .fontSize(7.5)
    .fillColor("#cbd5e1")
    .text(formatDate(new Date()), PAGE_WIDTH - 195, 76, {
      width: 130,
    });

  doc.y = 145;
}

function addSectionTitle(doc: PDFKit.PDFDocument, title: string) {
  ensureSpace(doc, 45);

  doc
    .font("Helvetica-Bold")
    .fontSize(13)
    .fillColor(colors.text)
    .text(title, PAGE_MARGIN, doc.y);

  doc
    .moveTo(PAGE_MARGIN, doc.y + 5)
    .lineTo(PAGE_WIDTH - PAGE_MARGIN, doc.y + 5)
    .strokeColor(colors.border)
    .lineWidth(1)
    .stroke();

  doc.moveDown(0.6);
}

function addSummaryCards(
  doc: PDFKit.PDFDocument,
  cards: Array<{
    label: string;
    value: string;
    tone: "blue" | "green" | "orange" | "red";
  }>
) {
  ensureSpace(doc, 90);

  const gap = 8;
  const cardWidth = (CONTENT_WIDTH - gap * 3) / 4;
  const cardHeight = 66;
  const y = doc.y;

  cards.slice(0, 4).forEach((card, index) => {
    const x = PAGE_MARGIN + index * (cardWidth + gap);

    const fill =
      card.tone === "green"
        ? colors.softGreen
        : card.tone === "orange"
          ? colors.softOrange
          : card.tone === "red"
            ? colors.softRed
            : colors.softBlue;

    const stroke =
      card.tone === "green"
        ? "#bbf7d0"
        : card.tone === "orange"
          ? "#fed7aa"
          : card.tone === "red"
            ? "#fecaca"
            : "#bfdbfe";

    const text =
      card.tone === "green"
        ? colors.green
        : card.tone === "orange"
          ? colors.orange
          : card.tone === "red"
            ? colors.red
            : colors.blue;

    doc
      .roundedRect(x, y, cardWidth, cardHeight, 10)
      .fillAndStroke(fill, stroke);

    doc
      .font("Helvetica-Bold")
      .fontSize(7.2)
      .fillColor(colors.muted)
      .text(card.label.toUpperCase(), x + 9, y + 12, {
        width: cardWidth - 18,
      });

    doc
      .font("Helvetica-Bold")
      .fontSize(11)
      .fillColor(text)
      .text(card.value, x + 9, y + 34, {
        width: cardWidth - 18,
        ellipsis: true,
      });
  });

  doc.y = y + cardHeight + 16;
}

function addInfoTable(
  doc: PDFKit.PDFDocument,
  rows: Array<[string, string | number]>
) {
  const rowHeight = 24;
  const labelWidth = 210;
  const valueWidth = CONTENT_WIDTH - labelWidth;

  rows.forEach(([label, value], index) => {
    ensureSpace(doc, rowHeight + 8);

    const y = doc.y;
    const fill = index % 2 === 0 ? "#f8fafc" : "#ffffff";

    doc
      .roundedRect(PAGE_MARGIN, y, CONTENT_WIDTH, rowHeight, 5)
      .fillAndStroke(fill, "#e2e8f0");

    doc
      .font("Helvetica-Bold")
      .fontSize(8.5)
      .fillColor(colors.muted)
      .text(label, PAGE_MARGIN + 10, y + 8, {
        width: labelWidth - 20,
      });

    doc
      .font("Helvetica")
      .fontSize(8.5)
      .fillColor(colors.text)
      .text(String(value), PAGE_MARGIN + labelWidth + 8, y + 8, {
        width: valueWidth - 18,
        ellipsis: true,
      });

    doc.y = y + rowHeight + 2;
  });

  doc.moveDown(0.3);
}

function addRecentLoansTable(doc: PDFKit.PDFDocument, rows: RecentLoanRow[]) {
  ensureSpace(doc, 80);

  const headers = ["Loan Type", "Member", "Amount", "Status", "Date"];
  const widths = [110, 115, 90, 115, 80];
  const headerHeight = 26;

  let y = doc.y;

  doc.roundedRect(PAGE_MARGIN, y, CONTENT_WIDTH, headerHeight, 6).fill("#eff6ff");

  let x = PAGE_MARGIN;

  headers.forEach((header, index) => {
    doc
      .font("Helvetica-Bold")
      .fontSize(8)
      .fillColor(colors.blue)
      .text(header, x + 8, y + 9, {
        width: widths[index] - 12,
      });

    x += widths[index];
  });

  doc.y = y + headerHeight + 3;

  if (rows.length === 0) {
    addInfoTable(doc, [["Recent Loans", "No recent loan records found"]]);
    return;
  }

  rows.forEach((item, rowIndex) => {
    ensureSpace(doc, 34);

    y = doc.y;
    x = PAGE_MARGIN;

    const fill = rowIndex % 2 === 0 ? "#ffffff" : "#f8fafc";

    doc.rect(PAGE_MARGIN, y, CONTENT_WIDTH, 30).fillAndStroke(fill, "#e2e8f0");

    const values = [
      item.type,
      item.member,
      formatCurrency(item.amount),
      formatStatus(item.status),
      formatDate(item.date),
    ];

    values.forEach((value, index) => {
      doc
        .font(index === 2 ? "Helvetica-Bold" : "Helvetica")
        .fontSize(7.8)
        .fillColor(index === 3 ? colors.orange : colors.text)
        .text(value, x + 8, y + 9, {
          width: widths[index] - 12,
          ellipsis: true,
        });

      x += widths[index];
    });

    doc.y = y + 32;
  });

  doc.moveDown(0.4);
}

async function getReportData() {
  const [
    totalMembers,
    activeMembers,
    pendingMembers,
    totalLoans,
    pendingLoans,
    offerSentLoans,
    financeProcessingLoans,
    approvedLoans,
    rejectedLoans,
    completedLoans,
    disbursedAmountResult,
    outstandingAmountResult,
    overdueAmountResult,
    repaymentResult,
    recentLoans,
  ] = await Promise.all([
    User.countDocuments({
      role: "member",
      isDeleted: { $ne: true },
    }),

    User.countDocuments({
      role: "member",
      accountStatus: "active",
      isDeleted: { $ne: true },
    }),

    User.countDocuments({
      role: "member",
      accountStatus: { $in: ["pending", "pending_admin_approval"] },
      isDeleted: { $ne: true },
    }),

    Loan.countDocuments(loanBaseFilter),

    Loan.countDocuments({
      ...loanBaseFilter,
      status: { $in: pendingStatuses },
    }),

    Loan.countDocuments({
      ...loanBaseFilter,
      status: "user_offer_pending",
    }),

    Loan.countDocuments({
      ...loanBaseFilter,
      status: { $in: ["user_accepted", "pending_finance_processing"] },
    }),

    Loan.countDocuments({
      ...loanBaseFilter,
      status: { $in: approvedOrProcessingStatuses },
    }),

    Loan.countDocuments({
      ...loanBaseFilter,
      status: { $in: rejectedStatuses },
    }),

    Loan.countDocuments({
      ...loanBaseFilter,
      status: "completed",
    }),

    Loan.aggregate([
      {
        $match: {
          ...loanBaseFilter,
          status: { $in: disbursedStatuses },
        },
      },
      {
        $group: {
          _id: null,
          total: { $sum: { $ifNull: ["$approvedAmount", 0] } },
        },
      },
    ]),

    Loan.aggregate([
      {
        $match: {
          ...loanBaseFilter,
          status: {
            $in: ["pending_finance_processing", "disbursed", "active", "overdue"],
          },
        },
      },
      {
        $group: {
          _id: null,
          total: { $sum: { $ifNull: ["$remainingBalance", 0] } },
        },
      },
    ]),

    Loan.aggregate([
      {
        $match: {
          ...loanBaseFilter,
          $or: [{ status: "overdue" }, { missedInstallments: { $gt: 0 } }],
        },
      },
      {
        $group: {
          _id: null,
          total: {
            $sum: {
              $add: [
                { $ifNull: ["$remainingBalance", 0] },
                { $ifNull: ["$lateFeeAmount", 0] },
              ],
            },
          },
        },
      },
    ]),

    Loan.aggregate([
      {
        $match: {
          ...loanBaseFilter,
          status: {
            $in: ["pending_finance_processing", "disbursed", "active", "completed"],
          },
        },
      },
      {
        $group: {
          _id: null,
          totalPaid: { $sum: { $ifNull: ["$paidAmount", 0] } },
          totalRepayment: { $sum: { $ifNull: ["$totalRepayment", 0] } },
        },
      },
    ]),

    Loan.find(loanBaseFilter)
      .populate("userId", "fullName email employeeId")
      .sort({ updatedAt: -1 })
      .limit(8)
      .lean(),
  ]);

  const disbursedAmount = Number(disbursedAmountResult?.[0]?.total || 0);
  const outstandingAmount = Number(outstandingAmountResult?.[0]?.total || 0);
  const overdueAmount = Number(overdueAmountResult?.[0]?.total || 0);

  const totalPaid = Number(repaymentResult?.[0]?.totalPaid || 0);
  const totalRepayment = Number(repaymentResult?.[0]?.totalRepayment || 0);

  const collectionRate =
    totalRepayment > 0 ? Math.round((totalPaid / totalRepayment) * 100) : 0;

  const recentActivity: RecentLoanRow[] = recentLoans.map((loan) => {
    const memberUser = loan.userId as PopulatedLoanUser | null | undefined;

    return {
      type: loan.loanType || "Loan",
      member: memberUser?.fullName || "Unknown Member",
      amount: Number(loan.approvedAmount || loan.requestedAmount || 0),
      status: loan.status || "unknown",
      date: loan.updatedAt || loan.createdAt,
    };
  });

  return {
    totalMembers,
    activeMembers,
    pendingMembers,
    totalLoans,
    pendingLoans,
    offerSentLoans,
    financeProcessingLoans,
    approvedLoans,
    rejectedLoans,
    completedLoans,
    disbursedAmount,
    outstandingAmount,
    overdueAmount,
    totalPaid,
    totalRepayment,
    collectionRate,
    recentActivity,
  };
}

function bufferToBlob(pdfBuffer: Buffer) {
  const arrayBuffer = new ArrayBuffer(pdfBuffer.byteLength);
  const uint8Array = new Uint8Array(arrayBuffer);

  uint8Array.set(pdfBuffer);

  return new Blob([uint8Array], {
    type: "application/pdf",
  });
}

export async function GET() {
  try {
    await dbConnect();

    const currentUser = await getCurrentUser();

    if (!currentUser) {
      return NextResponse.json(
        {
          success: false,
          message: "Unauthorized. Please login first.",
        },
        { status: 401 }
      );
    }

    if (currentUser.role !== "admin") {
      return NextResponse.json(
        {
          success: false,
          message: "Access denied. Admin only.",
        },
        { status: 403 }
      );
    }

    const reports = await getReportData();

    const pdfBuffer = await new Promise<Buffer>((resolve, reject) => {
      try {
        const doc = new PDFDocument({
          size: "A4",
          margin: PAGE_MARGIN,
          bufferPages: true,
          info: {
            Title: "Admin Reports & Analytics",
            Author: "Welfare",
            Subject: "Welfare Admin Report",
          },
        });

        const chunks: Buffer[] = [];

        doc.on("data", (chunk: Buffer) => chunks.push(chunk));
        doc.on("end", () => resolve(Buffer.concat(chunks)));
        doc.on("error", reject);

        addHeader(
          doc,
          currentUser.fullName || currentUser.email || "Main Admin"
        );

        addSummaryCards(doc, [
          {
            label: "Total Members",
            value: String(reports.totalMembers),
            tone: "blue",
          },
          {
            label: "Total Loans",
            value: String(reports.totalLoans),
            tone: "green",
          },
          {
            label: "Disbursed",
            value: formatCurrency(reports.disbursedAmount),
            tone: "orange",
          },
          {
            label: "Overdue",
            value: formatCurrency(reports.overdueAmount),
            tone: "red",
          },
        ]);

        addSectionTitle(doc, "1. Member Summary");

        addInfoTable(doc, [
          ["Total Members", reports.totalMembers],
          ["Active Members", reports.activeMembers],
          ["Pending Members", reports.pendingMembers],
        ]);

        addSectionTitle(doc, "2. Loan Workflow Summary");

        addInfoTable(doc, [
          ["Total Loan Applications", reports.totalLoans],
          ["Pending Review Loans", reports.pendingLoans],
          ["Offer Sent Loans", reports.offerSentLoans],
          ["Finance Processing Loans", reports.financeProcessingLoans],
          ["Approved / Processing Loans", reports.approvedLoans],
          ["Rejected Loans", reports.rejectedLoans],
          ["Completed Loans", reports.completedLoans],
        ]);

        addSectionTitle(doc, "3. Finance Summary");

        addInfoTable(doc, [
          ["Disbursed Amount", formatCurrency(reports.disbursedAmount)],
          ["Outstanding Amount", formatCurrency(reports.outstandingAmount)],
          ["Overdue Amount", formatCurrency(reports.overdueAmount)],
          ["Paid Amount", formatCurrency(reports.totalPaid)],
          ["Total Repayment Value", formatCurrency(reports.totalRepayment)],
          ["Collection Rate", `${reports.collectionRate}%`],
        ]);

        addSectionTitle(doc, "4. Recent Loan Activity");

        addRecentLoansTable(doc, reports.recentActivity);

        addSectionTitle(doc, "5. Report Note");

        addInfoTable(doc, [
          [
            "Note",
            "This report is generated automatically from the Welfare database and should be used for administrative review and monitoring purposes.",
          ],
          ["Generated At", formatDate(new Date())],
        ]);

        addFooter(doc, 1);
        doc.end();
      } catch (error) {
        reject(error);
      }
    });

    const pdfBlob = bufferToBlob(pdfBuffer);

    return new Response(pdfBlob, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="welfare-admin-report-${Date.now()}.pdf"`,
      },
    });
  } catch (error) {
    console.error("EXPORT_ADMIN_REPORT_PDF_ERROR", error);

    return NextResponse.json(
      {
        success: false,
        message:
          error instanceof Error
            ? error.message
            : "Failed to export admin report PDF.",
      },
      { status: 500 }
    );
  }
}